CREATE TABLE [User] (
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100) NOT NULL,
	SecondName NVARCHAR(100) NOT NULL
);

CREATE TABLE Category (
	Id INT PRIMARY KEY IDENTITY,
	Description NVARCHAR(100) NOT NULL,
);

CREATE TABLE Project (
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100) NOT NULL,
	Description NVARCHAR(100) NOT NULL,
	CreationDate DATETIME,
	CreatorId INT,
	CategoryId INT,
	CONSTRAINT FK_Project_User FOREIGN KEY (CreatorId) REFERENCES [User](Id) ON DELETE CASCADE,
	CONSTRAINT FK_Project_Category FOREIGN KEY (CategoryId) REFERENCES Category(Id) ON DELETE CASCADE
);

CREATE TABLE Comment (
	Id INT PRIMARY KEY IDENTITY,
	Text NVARCHAR(100) NOT NULL,
	Date DATETIME,
	UserId INT,
	ProjectId INT,
	CONSTRAINT FK_Comment_User FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE SET NULL,
	CONSTRAINT FK_Comment_Project FOREIGN KEY (ProjectId) REFERENCES [Project](Id) ON DELETE NO ACTION
);

CREATE TABLE Vote (
	Id INT PRIMARY KEY IDENTITY,
	UserId INT,
	ProjectId INT,
	CONSTRAINT UQ_Vote_User_Project UNIQUE(UserId, ProjectId),
	CONSTRAINT FK_Vote_User FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE NO ACTION,
	CONSTRAINT FK_Vote_Project FOREIGN KEY (ProjectId) REFERENCES Project(Id) ON DELETE NO ACTION
);